### ISSUE TITLE
cliff.delta missing values issue

### ISSUE THREAD

**Issue by psrdwy** [mtorchiano/effsize#50]
I'm sorry to add potentially more stress at what I'm sure is a difficult time due to the COVID-19 pandemic - we are all under shelter in place orders where I am, and I'm sure it is much worse where you are - but I ran into this problem.  When NA values are inputted into Cliff's delta, it seems to yield a different result from when they are excluded.  Here is an example:

```
cliff.delta(master_TD$vine_adaptive_ss,
             master_ASD$vine_adaptive_ss,use.normal=F)

cliff.delta(master_TD$vine_adaptive_ss[which(master_TD$vine_adaptive_ss>0)],
             master_ASD$vine_adaptive_ss[which(master_ASD$vine_adaptive_ss>0)],use.normal=F)

cliff.delta(master_TD$vine_adaptive_ss[which(!is.na(master_TD$vine_adaptive_ss))],
            master_ASD$vine_adaptive_ss[which(!is.na(master_ASD$vine_adaptive_ss))],use.normal=F)
```

The former yields an effect of .75, but the second and third ones give an effect size of .97.

There is no conflict among these instances when return.dm = TRUE is specified; all three of the following yield effect size .97:

```
cliff.delta(master_TD$vine_adaptive_ss,
            master_ASD$vine_adaptive_ss,use.normal=F,return.dm=TRUE)

cliff.delta(master_TD$vine_adaptive_ss[which(master_TD$vine_adaptive_ss>0)],
            master_ASD$vine_adaptive_ss[which(master_ASD$vine_adaptive_ss>0)],use.normal=F,return.dm=TRUE)

cliff.delta(master_TD$vine_adaptive_ss[which(!is.na(master_TD$vine_adaptive_ss))],
            master_ASD$vine_adaptive_ss[which(!is.na(master_ASD$vine_adaptive_ss))],use.normal=F,return.dm=TRUE)
```

I am using effsize 0.7.6.

**Comment by mtorchiano** [comment]
Sorry for the late reply, I'm currently quite busy in giving online lectures...

I think that problem was fixed in later versions where you can use `na.rm=TRUE` to remove `NA`s.

Anyway, if you send me a Minimal Working Example I'll have a look into it.

**Comment by psrdwy** [comment]
No worries; certainly an unusual situation at the moment!  Here you go:
```
mtcars = mtcars
set.seed(12345)
vals = sample(1:length(mtcars$mpg), 10, replace=FALSE)
mtcars$mpg[vals] = NA
library(effsize)
cliff.delta(mtcars$mpg[which(mtcars$vs==0)],
            mtcars$mpg[which(mtcars$vs==1)])
cliff.delta(mtcars$mpg[which(mtcars$vs==0)],
            mtcars$mpg[which(mtcars$vs==1)],
            return.dm=TRUE)
```
The former returns -0.80 and the latter -0.73.  I upgraded to 0.7.9 and still get the issue.

**Comment by mtorchiano** [comment]
There was a problem in the code, size of the two arrays were computed before removing the `NA`s.
